{
    "name": "Library Management",
    "version": "16.0.1.0.0",
    "category": "Services/Library",
    "summary": "Manage books, members, borrowing, and library KPIs",
    "author": "Phuong",
    "depends": ["base", "web", "stock", "product"],
    "data": [
        "security/library_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/stock_location.xml",
        "data/stock_picking_type.xml",
        "views/dashboard_views.xml",
        "views/product_template_views.xml",
        "views/category_views.xml",
        "views/library_author_views.xml",
        "views/publisher_views.xml",
        "views/self_views.xml",
        "views/stock_production_lot_views.xml",
        "views/library_member_views.xml",
        "views/library_borrow_views.xml",
        "views/library_menu.xml",
    ],
    "demo": [
        "demo/library_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "library_management/static/src/js/dashboard.js",
            "library_management/static/src/xml/dashboard.xml",
            "library_management/static/src/css/dashboard.css",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
